language: node_js

node_js:
  - '11.6.0'

cache:
  yarn: true

env:
  NODE_ENV: 'release'

branches:
  only:
    - master

before_install:
  - npm i -g yarn

install:
  - yarn global add codecov
  - yarn install

script:
  - yarn test
  - codecov
