name: Lints

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NODE_ENV: release

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
